# Generated by Django 4.0 on 2022-01-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('S', 'Standard Item'), ('P', 'Prime Item'), ('M', 'Mod')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
