# Generated by Django 4.0 on 2022-01-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ducats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rank',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
